### ISSUE TITLE
Full-size SD version?

### ISSUE THREAD

**Issue by iaros** [citrus3000psi/SD2SP2#2]
Hello, and thank you for such an interesting concept and implementation to use the NGC's second port.

Would it be possible to adapt this solution for a full-sized SD card (because many people who would switch from wii-sd already have full-size cards which they already tested to work with swiss)?

Regards

**Comment by citrus3000psi** [comment]
In its current form no, perhaps with a multi piece pcb you could some how make it work.  But would be a manufacturing nightmare.
