### ISSUE TITLE
Capacitor Size

### ISSUE THREAD

**Issue by rickdgray** [citrus3000psi/SD2SP2#4]
Conventional wisdom on bypass capacitors is to use something like 0.1uF, but I see you chose to use a 22uF. I'm just curious how you came to that number.

**Comment by Ancyker** [comment]
Pretty sure it's for decoupling and not bypassing. The schematic has 0.1uF (".1") marked though the README calls for 22uF, so I'd guess that 0.1uF didn't work. Looking at the SD card spec data I found, it seems 0.1-40uF is recommended on VCC for decoupling, with the value going up the further away the card is from the power supply. Seeing as power has to go from under the GC mainboard, through the mainboard, through the SP2 slot, and into the reader, 22uF sounds reasonable to me. I found several SD readers intended for the Arduino that use 22uF (and some that use both 0.1uF and 22uF).

**Comment by rickdgray** [comment]
Informative; thanks!
